parameters:
    json_schema.generator.class:                "Knp\\JsonSchemaBundle\\Schema\\SchemaGenerator"
    json_schema.builder.class:                  "Knp\\JsonSchemaBundle\\Schema\\SchemaBuilder"
    json_schema.validator.class:                "JsonSchema\\Validator"
    json_schema.builder.handler.blank.class:    "Knp\\JsonSchemaBundle\\Constraints\\BlankConstraintHandler"
    json_schema.builder.handler.choice.class:   "Knp\\JsonSchemaBundle\\Constraints\\ChoiceConstraintHandler"
    json_schema.builder.handler.notblank.class: "Knp\\JsonSchemaBundle\\Constraints\\NotBlankConstraintHandler"
    json_schema.builder.handler.regex.class:    "Knp\\JsonSchemaBundle\\Constraints\\RegexConstraintHandler"
    json_schema.builder.handler.type.class:     "Knp\\JsonSchemaBundle\\Constraints\\TypeConstraintHandler"

services:
    json_schema.generator:
        class: %json_schema.generator.class%
        arguments:
            - @validator.mapping.class_metadata_factory
            - @json_schema.validator
            - @json_schema.builder

    json_schema.builder:
        public: false
        class: %json_schema.builder.class%

    json_schema.validator:
        public: false
        class: %json_schema.validator.class%

    json_schema.builder.handler.blank:
        public: false
        class: %json_schema.builder.handler.blank.class%
        tags:
            - { name: json_schema.builder.handler, priority: 1 }

    json_schema.builder.handler.choice:
        public: false
        class: %json_schema.builder.handler.choice.class%
        tags:
            - { name: json_schema.builder.handler, priority: 2 }

    json_schema.builder.handler.notblank:
        public: false
        class: %json_schema.builder.handler.notblank.class%
        tags:
            - { name: json_schema.builder.handler, priority: 3 }

    json_schema.builder.handler.regex:
        public: false
        class: %json_schema.builder.handler.regex.class%
        tags:
            - { name: json_schema.builder.handler, priority: 4 }

    json_schema.builder.handler.type:
        public: false
        class: %json_schema.builder.handler.type.class%
        tags:
            - { name: json_schema.builder.handler, priority: 5 }
