parameters:
    json_schema.generator.class:                "Knp\\JsonSchemaBundle\\Schema\\SchemaGenerator"
    json_schema.builder.class:                  "Knp\\JsonSchemaBundle\\Schema\\SchemaBuilder"
    json_schema.validator.class:                "JsonSchema\\Validator"
    json_schema.builder.handler.validator_type_guesser_handler.class:     "Knp\\JsonSchemaBundle\\Constraints\\ValidatorTypeGuesserHandler"

services:
    json_schema.generator:
        class: %json_schema.generator.class%
        arguments:
            - @validator.mapping.class_metadata_factory
            - @json_schema.validator
            - @json_schema.builder

    json_schema.builder:
        public: false
        class: %json_schema.builder.class%

    json_schema.validator:
        public: false
        class: %json_schema.validator.class%

    json_schema.builder.handler.validator_type_guesser:
        public: false
        class: %json_schema.builder.handler.validator_type_guesser_handler.class%
        arguments:
            - @form.type_guesser.validator
        tags:
            - { name: json_schema.builder.handler, priority: 5 }
