parameters:
    json_schema.generator.class: "Knp\\JsonSchemaBundle\\Schema\\SchemaGenerator"
    json_schema.builder.class:   "Knp\\JsonSchemaBundle\\Schema\\SchemaBuilder"
    json_schema.validator.class: "JsonSchema\\Validator"

services:
    json_schema.generator:
        class: %json_schema.generator.class%
        arguments:
            - @validator.mapping.class_metadata_factory
            - @json_schema.validator
            - @json_schema.builder

    json_schema.builder:
        public: false
        class: %json_schema.builder.class%

    json_schema.validator:
        public: false
        class: %json_schema.validator.class%
