show_json_schema:
    pattern: /schemas/{alias}.json
    defaults: { _controller: KnpJsonSchemaBundle:Schema:show }

index_json_schema:
    pattern: /schemas.json
    defaults: { _controller: KnpJsonSchemaBundle:Schema:index }
