parameters:
    json_schema.generator.class:                                            "Knp\\JsonSchemaBundle\\Schema\\SchemaGenerator"
    json_schema.registry.class:                                             "Knp\\JsonSchemaBundle\\Schema\\SchemaRegistry"
    json_schema.reflection_factory.class:                                   "Knp\\JsonSchemaBundle\\Reflection\\ReflectionFactory"
    json_schema.property.handler.form_type_guesser_handler.class:           "Knp\\JsonSchemaBundle\\Property\\FormTypeGuesserHandler"
    json_schema.property.handler.extra_validator_constraints_handler.class: "Knp\\JsonSchemaBundle\\Property\\ExtraValidatorConstraintsHandler"
    json_schema.property.handler.annotation.class:                          "Knp\\JsonSchemaBundle\\Property\\JsonSchemaAnnotationHandler"
    json_schema.response.factory.class:                                     "Knp\\JsonSchemaBundle\\HttpFoundation\\JsonResponseFactory"
    json_schema.factory.schema.class:                                       "Knp\\JsonSchemaBundle\\Model\\SchemaFactory"
    json_schema.factory.property.class:                                     "Knp\\JsonSchemaBundle\\Model\\PropertyFactory"
    json_schema.validator.class:                                            "JsonSchema\\Validator"
    form.chain.guesser.class:                                               "Symfony\\Component\\Form\\FormTypeGuesserChain"

services:
    json_schema.generator:
        class: %json_schema.generator.class%
        arguments:
            - @json_schema.validator
            - @router
            - @json_schema.reflection_factory
            - @json_schema.registry
            - @json_schema.factory.schema
            - @json_schema.factory.property

    json_schema.registry:
        public: false
        class: %json_schema.registry.class%

    json_schema.factory.schema:
        public: false
        class: %json_schema.factory.schema.class%

    json_schema.factory.property:
        public: false
        class: %json_schema.factory.property.class%

    json_schema.reflection_factory:
        public: false
        class: %json_schema.reflection_factory.class%
        arguments:
            - @json_schema.finder
            - @json_schema.filesystem

    json_schema.finder:
        public: false
        class: "Symfony\\Component\\Finder\\Finder"

    json_schema.filesystem:
        public: false
        class: "Symfony\\Component\\Filesystem\\Filesystem"

    json_schema.validator:
        public: false
        class: %json_schema.validator.class%

    json_schema.response.factory:
        class: %json_schema.response.factory.class%
        arguments:
            - @json_schema.registry
            - @router

    json_schema.property.handler.annotation:
        public: false
        class: %json_schema.property.handler.annotation.class%
        arguments:
            - @annotation_reader
            - @json_schema.reflection_factory
        tags:
            - { name: json_schema.property.handler, priority: 0 }

    json_schema.property.handler.chained_guesser:
        public: false
        class: %json_schema.property.handler.form_type_guesser_handler.class%
        arguments:
            - @form.chain.guesser
            - @json_schema.registry
        tags:
            - { name: json_schema.property.handler, priority: 10 }

    json_schema.property.handler.extra_validator_constraints_handler:
        public: false
        class: %json_schema.property.handler.extra_validator_constraints_handler.class%
        arguments:
            - @validator.mapping.class_metadata_factory
        tags:
            - { name: json_schema.property.handler, priority: 20 }

    form.chain.guesser:
        public: false
        class: %form.chain.guesser.class%
        arguments:
            - [@form.type_guesser.validator, @form.type_guesser.doctrine]
